# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Variable-Strongly-Typed
version:      v1.1.0
version_from: lib/Variable/Strongly/Typed.pm
installdirs:  site
requires:
    Attribute::Handlers:           0
    Class::Std::Utils:             0
    IO::File:                      0
    Test::More:                    0
    Tie::Array:                    0
    Tie::Hash:                     0
    Tie::Scalar:                   0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
